# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "CV cổ điển"
  url = "#post-cv"
  weight = 20

[[main]]
  name = "CV hiện đại"
  url = "#post-mcv"
  weight = 30

[[main]]
  name = "Ứng dụng"
  url = "#post-tech"
  weight = 40

[[main]]
  name = "Toán cho CS"
  url = "#post-math"
  weight = 50



[[main]]
  name = "Đặt câu hỏi"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
